pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'betterbees'

['1.21.1', '1.21.4', '1.21.8', '1.21.11', '26.1.2', '26.2'].each { minecraftVersion ->
    def projectName = "mc${minecraftVersion.replace('.', '_')}"
    include(projectName)
    project(":${projectName}").projectDir = file("versions/${minecraftVersion}")
}
